import { StyleSheet } from "react-native";

export const palette = {
  bg: "#050507",
  bgSoft: "#0d0d12",
  panel: "#111116",
  panelSoft: "#17171f",
  panelStrong: "#1c0f12",
  text: "#f4eee8",
  muted: "#9d96a3",
  red: "#c30d12",
  redSoft: "#6a1118",
  cyan: "#73f6dd",
  amber: "#ffcf6a",
  border: "rgba(255,255,255,0.08)",
  sold: "#494855",
  held: "#5e6a80",
  seat: "#e9e2d8",
  vip: "#ffcf6a",
  couple: "#c93f62",
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: palette.bg },
  routeFrame: { flex: 1 },
  swipeBackCue: {
    position: "absolute",
    left: 0,
    top: 84,
    bottom: 18,
    width: 5,
    borderTopRightRadius: 999,
    borderBottomRightRadius: 999,
    backgroundColor: "rgba(115,246,221,0.7)",
    shadowColor: palette.cyan,
    shadowOpacity: 0.42,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 0 },
    elevation: 12,
  },
  topBar: {
    paddingHorizontal: 18,
    paddingTop: 14,
    paddingBottom: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(195,13,18,0.18)",
    backgroundColor: "#0b0b10",
  },
  brandWrap: { flexDirection: "row", alignItems: "center", gap: 12, flexShrink: 1 },
  brandLogo: {
    width: 44,
    height: 44,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#130709",
    borderWidth: 1,
    borderColor: "rgba(255,120,120,0.28)",
    shadowColor: palette.red,
    shadowOpacity: 0.34,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 4 },
  },
  brandLogoImage: { width: 30, height: 30 },
  brandMeta: { gap: 1, flexShrink: 1 },
  brandCaption: { color: "#b89398", fontSize: 9, fontWeight: "900", letterSpacing: 1.4 },
  brand: { color: "#fff4ef", fontSize: 19, fontWeight: "900", letterSpacing: 0.45 },
  topBarStatusWrap: { flexDirection: "row", alignItems: "center", gap: 10 },
  networkIndicator: {
    width: 24,
    height: 24,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.02)",
    borderWidth: 1.5,
  },
  networkIndicatorOnline: { borderColor: "rgba(70,210,120,0.95)", shadowColor: "#33d17a", shadowOpacity: 0.28, shadowRadius: 8, shadowOffset: { width: 0, height: 2 } },
  networkIndicatorOffline: { borderColor: "rgba(195,13,18,0.95)", shadowColor: palette.red, shadowOpacity: 0.28, shadowRadius: 8, shadowOffset: { width: 0, height: 2 } },
  networkIndicatorCore: { width: 10, height: 10, borderRadius: 999 },
  networkIndicatorCoreOnline: { backgroundColor: "#33d17a" },
  networkIndicatorCoreOffline: { backgroundColor: "#c30d12" },
  liveClock: {
    minWidth: 72,
    color: palette.text,
    fontSize: 13,
    fontWeight: "800",
    textAlign: "right",
    fontVariant: ["tabular-nums"],
  },
  scrollContent: { paddingHorizontal: 18, paddingTop: 18, paddingBottom: 150, gap: 18 },
  toast: {
    position: "absolute",
    top: 34,
    alignSelf: "center",
    minWidth: 156,
    maxWidth: 336,
    paddingLeft: 8,
    paddingRight: 14,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: "rgba(10,10,14,0.96)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    zIndex: 40,
    shadowColor: "#000",
    shadowOpacity: 0.28,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 16,
  },
  toastSuccess: { borderColor: "rgba(115,246,221,0.48)", backgroundColor: "rgba(5,36,31,0.98)" },
  toastError: { borderColor: "rgba(255,107,107,0.46)", backgroundColor: "rgba(52,10,15,0.98)" },
  toastIconWrap: { width: 28, height: 28, borderRadius: 999, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "rgba(255,255,255,0.08)" },
  toastIconWrapSuccess: { borderColor: "rgba(138,255,234,0.34)", shadowColor: palette.cyan, shadowOpacity: 0.24, shadowRadius: 10, shadowOffset: { width: 0, height: 4 } },
  toastIconWrapError: { borderColor: "rgba(255,141,141,0.3)", shadowColor: "#ff6b6b", shadowOpacity: 0.22, shadowRadius: 10, shadowOffset: { width: 0, height: 4 } },
  toastBody: { flexShrink: 1, gap: 2, paddingRight: 6 },
  toastHeader: { flexDirection: "row", alignItems: "center", gap: 5 },
  toastDot: { width: 6, height: 6, borderRadius: 999, backgroundColor: palette.amber },
  toastDotSuccess: { backgroundColor: palette.cyan },
  toastDotError: { backgroundColor: "#ff6b6b" },
  toastLabel: { color: palette.text, fontSize: 9, fontWeight: "900", letterSpacing: 0.35 },
  toastTone: { color: palette.muted, fontSize: 9, fontWeight: "800", letterSpacing: 0.35 },
  toastToneSuccess: { color: "#8affea" },
  toastToneError: { color: "#ff9a9a" },
  toastMessageViewport: { overflow: "hidden", alignSelf: "stretch" },
  toastMessageRail: { alignSelf: "flex-start" },
  toastText: { color: palette.text, fontWeight: "700", lineHeight: 14, fontSize: 10, flexShrink: 1 },
  toastTextMeasure: { position: "absolute", opacity: 0, left: -9999, top: -9999 },
  toastProgressTrack: { height: 2, borderRadius: 999, backgroundColor: "rgba(255,255,255,0.08)", overflow: "hidden", marginTop: 2, position: "relative" },
  toastProgressFill: { height: "100%", borderRadius: 999, backgroundColor: palette.amber, shadowOpacity: 0.5, shadowRadius: 6, shadowOffset: { width: 0, height: 0 } },
  toastProgressFillSuccess: { backgroundColor: palette.cyan },
  toastProgressFillError: { backgroundColor: "#ff7b7b" },
  toastProgressGlow: { position: "absolute", left: 0, right: 0, top: -2, height: 2, borderRadius: 999, opacity: 0.8 },
  toastProgressShimmer: { position: "absolute", top: -3, bottom: -3, width: 56, borderRadius: 999, backgroundColor: "rgba(255,255,255,0.18)", opacity: 0.38, transform: [{ skewX: "-18deg" }] },
  skeletonBlock: { borderRadius: 24, backgroundColor: palette.panel, borderWidth: 1, borderColor: palette.border },

  heroCard: { minHeight: 396, borderRadius: 28, padding: 22, justifyContent: "space-between", overflow: "hidden", borderWidth: 1, borderColor: "rgba(195,13,18,0.18)" },
  heroImage: { ...StyleSheet.absoluteFillObject, opacity: 0.32 },
  heroOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(7,7,10,0.46)" },
  heroTopLine: { zIndex: 1, flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  eyebrow: { color: palette.amber, fontSize: 11, fontWeight: "800", letterSpacing: 1.4 },
  heroTag: { color: "#fff5ef", fontSize: 12, fontWeight: "800", paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, backgroundColor: "rgba(195,13,18,0.22)" },
  heroContent: { zIndex: 1, gap: 7, marginTop: 36 },
  heroKicker: { color: "#ffe0d9", fontSize: 12, fontWeight: "800", letterSpacing: 1.6 },
  heroTitle: { color: palette.text, fontSize: 34, lineHeight: 38, fontWeight: "900" },
  heroSubline: { color: "#efe5df", fontSize: 13, fontWeight: "700" },
  heroBody: { color: "#ddd3cc", fontSize: 14, lineHeight: 21, maxWidth: 300 },
  heroMetrics: { zIndex: 1, flexDirection: "row", flexWrap: "wrap", gap: 8 },
  metricItem: { flexGrow: 1, minWidth: "31%", borderRadius: 14, padding: 12, backgroundColor: "rgba(8,8,12,0.45)", borderWidth: 1, borderColor: "rgba(255,255,255,0.08)" },
  metricLabel: { color: "#c6bec6", fontSize: 11, fontWeight: "700" },
  metricValue: { color: "#fff", fontSize: 15, fontWeight: "900", marginTop: 6 },
  heroActions: { zIndex: 1, flexDirection: "row", gap: 8, marginTop: 6 },

  quickStrip: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  quickStripItem: { flexGrow: 1, minWidth: "31%", padding: 14, borderRadius: 16, backgroundColor: palette.panel, borderWidth: 1, borderColor: palette.border },
  quickStripLabel: { color: palette.muted, fontSize: 11, fontWeight: "700" },
  quickStripValue: { color: palette.text, fontSize: 15, fontWeight: "900", marginTop: 6 },

  button: { paddingHorizontal: 17, paddingVertical: 12, borderRadius: 999, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 8 },
  buttonDisabled: { opacity: 0.72 },
  buttonPrimary: { backgroundColor: palette.red },
  buttonSecondary: { borderWidth: 1, borderColor: "rgba(255,255,255,0.18)", backgroundColor: "rgba(7,7,10,0.24)" },
  buttonText: { fontSize: 13, fontWeight: "800" },
  buttonTextPrimary: { color: "#fff8f6" },
  buttonTextSecondary: { color: palette.text },

  sectionHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  sectionTitle: { color: palette.text, fontSize: 22, fontWeight: "900" },
  sectionAction: { color: palette.amber, fontSize: 12, fontWeight: "800" },
  row: { gap: 10, paddingRight: 10 },

  bannerCard: { minHeight: 144, borderRadius: 22, padding: 18, justifyContent: "flex-end", overflow: "hidden" },
  bannerImage: { borderRadius: 22, opacity: 0.24 },
  bannerOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(10,10,15,0.3)" },
  bannerEyebrow: { color: "#f4d7d1", fontSize: 11, fontWeight: "800", letterSpacing: 0.8 },
  bannerTitle: { color: "#fff", fontSize: 24, fontWeight: "900", marginTop: 6 },
  bannerText: { color: "#efe6e4", fontSize: 13, lineHeight: 19, marginTop: 6, maxWidth: 300 },

  movieCard: { width: 168, gap: 8 },
  savedMovieCardFavorite: { borderWidth: 1, borderColor: "rgba(201,63,98,0.34)" },
  savedMovieCardWatchlist: { borderWidth: 1, borderColor: "rgba(115,246,221,0.28)" },
  savedMovieCardBoth: { borderWidth: 1, borderColor: "rgba(255,198,166,0.34)", shadowColor: "#c93f62", shadowOpacity: 0.12, shadowRadius: 10, shadowOffset: { width: 0, height: 4 } },
  posterTopRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", gap: 8 },
  poster: { height: 228, borderRadius: 20, justifyContent: "space-between", padding: 12, overflow: "hidden" },
  posterImage: { borderRadius: 20 },
  posterScrim: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(10,10,15,0.18)" },
  posterBadge: { color: "#fff", fontSize: 11, fontWeight: "800", paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, backgroundColor: "rgba(9,9,12,0.52)", alignSelf: "flex-start" },
  movieStateBadgeRow: { flexDirection: "row", alignItems: "center", gap: 6, flexWrap: "wrap", alignSelf: "flex-start" },
  movieStateBadgeRowCompact: { gap: 4 },
  movieStateBadge: { flexDirection: "row", alignItems: "center", gap: 5, paddingHorizontal: 8, paddingVertical: 5, borderRadius: 999, borderWidth: 1 },
  movieStateBadgeCompact: { paddingHorizontal: 6, paddingVertical: 4, gap: 0 },
  movieStateBadgeFavorite: { backgroundColor: "rgba(201,63,98,0.88)", borderColor: "rgba(255,206,220,0.22)" },
  movieStateBadgeWatchlist: { backgroundColor: "rgba(17,120,91,0.88)", borderColor: "rgba(180,255,231,0.18)" },
  movieStateBadgeText: { color: "#fff7f4", fontSize: 10, fontWeight: "900" },
  movieTitle: { color: palette.text, fontSize: 17, fontWeight: "800" },
  movieMeta: { color: palette.muted, fontSize: 12, lineHeight: 18 },
  movieFooter: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  movieScore: { color: palette.amber, fontWeight: "900", fontSize: 12 },
  movieAction: { color: palette.text, fontWeight: "700", fontSize: 12 },

  rankingWrap: { gap: 12 },
  rankingRow: { flexDirection: "row", alignItems: "center", gap: 12, padding: 13, borderRadius: 18, backgroundColor: palette.panel, borderWidth: 1, borderColor: palette.border },
  rankPoster: { width: 42, height: 56, borderRadius: 12 },
  rankMain: { flex: 1, gap: 4 },
  rankMovie: { color: palette.text, fontWeight: "800", fontSize: 16 },
  rankRevenue: { color: palette.muted, fontSize: 12, fontWeight: "700" },
  rankActionText: { color: palette.amber, fontWeight: "800", fontSize: 12 },
  homeGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  homeGridCard: { width: "48.2%", backgroundColor: palette.panel, borderRadius: 20, overflow: "hidden", borderWidth: 1, borderColor: palette.border },
  homeGridPoster: { height: 172, backgroundColor: palette.panelSoft, justifyContent: "space-between", padding: 12 },
  homeGridPosterImage: { width: "100%", height: "100%" },
  homeGridBody: { padding: 14, gap: 6 },
  homeGridTitle: { color: palette.text, fontSize: 16, fontWeight: "900" },
  homeGridMeta: { color: palette.muted, fontSize: 12, lineHeight: 18 },
  homeGridFooter: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 10, marginTop: 2 },
  homeGridAction: { color: palette.cyan, fontSize: 12, fontWeight: "800" },

  exploreHero: { padding: 18, borderRadius: 22, backgroundColor: palette.panelStrong, borderWidth: 1, borderColor: "rgba(195,13,18,0.18)", gap: 8 },
  exploreCard: { backgroundColor: palette.panel, borderRadius: 22, overflow: "hidden", borderWidth: 1, borderColor: palette.border },
  explorePoster: { height: 188, backgroundColor: palette.panelSoft },
  explorePosterImage: { width: "100%", height: "100%" },
  explorePosterOverlay: { position: "absolute", top: 12, right: 12 },
  exploreBody: { padding: 16, gap: 6 },
  exploreBadge: { color: palette.amber, fontSize: 11, fontWeight: "800" },
  exploreTitle: { color: palette.text, fontSize: 20, fontWeight: "900" },
  exploreMeta: { color: palette.cyan, fontSize: 12, fontWeight: "700" },
  exploreDescription: { color: palette.muted, lineHeight: 21 },

  screenIntro: { gap: 6 },
  ticketCard: { backgroundColor: palette.panel, borderRadius: 22, borderWidth: 1, borderColor: palette.border, overflow: "hidden", gap: 8, paddingBottom: 16 },
  ticketEmptyCard: { backgroundColor: palette.panelStrong, borderRadius: 22, borderWidth: 1, borderColor: "rgba(195,13,18,0.18)", padding: 16, gap: 12 },
  ticketEmptyLabel: { color: palette.amber, fontSize: 11, fontWeight: "800", letterSpacing: 1.4 },
  ticketStripe: { height: 5, backgroundColor: palette.red },
  ticketHead: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 10 },
  ticketMovieHead: { flex: 1, gap: 6 },
  ticketContent: { paddingHorizontal: 18, paddingTop: 18, gap: 6 },
  ticketMovie: { color: palette.text, fontSize: 18, fontWeight: "900" },
  ticketInfo: { color: palette.muted, lineHeight: 19 },
  ticketStatus: { color: "#f4e0da", fontSize: 11, fontWeight: "800", borderWidth: 1, borderColor: "rgba(255,255,255,0.08)", backgroundColor: "rgba(255,255,255,0.06)", borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6 },
  ticketStatusPaid: { color: "#ddfff7", borderColor: "rgba(115,246,221,0.24)", backgroundColor: "rgba(115,246,221,0.12)" },
  ticketStatusLoading: { minWidth: 42, alignItems: "center", justifyContent: "center", paddingVertical: 5 },

  authHero: { padding: 24, borderRadius: 28, backgroundColor: palette.panelStrong, borderWidth: 1, borderColor: "rgba(195,13,18,0.2)", gap: 10 },
  authTitle: { color: palette.text, fontSize: 28, lineHeight: 34, fontWeight: "900" },
  authBody: { color: "#ddd3cc", fontSize: 14, lineHeight: 22 },
  authFeatureRow: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginTop: 4 },
  authFeatureChip: { paddingHorizontal: 12, paddingVertical: 10, borderRadius: 999, backgroundColor: "rgba(255,255,255,0.06)", borderWidth: 1, borderColor: "rgba(255,255,255,0.08)" },
  authFeatureText: { color: palette.text, fontSize: 12, fontWeight: "800" },
  authStepRow: { flexDirection: "row", justifyContent: "center", gap: 8, marginTop: -2 },
  authStepDot: { width: 9, height: 9, borderRadius: 999, backgroundColor: "rgba(255,255,255,0.14)" },
  authStepDotActive: { width: 26, backgroundColor: palette.red },
  authNavRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  authLink: { color: palette.cyan, fontSize: 13, fontWeight: "800" },
  authCard: { padding: 20, borderRadius: 24, backgroundColor: palette.panel, borderWidth: 1, borderColor: palette.border, gap: 10 },
  googleButton: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 10, paddingHorizontal: 18, paddingVertical: 14, borderRadius: 999, backgroundColor: "#1f4fd8", borderWidth: 1, borderColor: "rgba(255,255,255,0.08)" },
  googleButtonText: { color: "#ffffff", fontSize: 13, fontWeight: "900" },
  authDivider: { color: palette.muted, fontSize: 12, fontWeight: "700", textAlign: "center", marginVertical: 2 },

  profileHero: { flexDirection: "row", alignItems: "center", gap: 16, backgroundColor: palette.panelStrong, borderWidth: 1, borderColor: "rgba(195,13,18,0.18)", borderRadius: 26, padding: 20 },
  profileMetaBlock: { flex: 1, gap: 4 },
  avatar: { width: 62, height: 62, borderRadius: 999, backgroundColor: "#2b0e12", borderWidth: 1, borderColor: "rgba(195,13,18,0.4)" },
  profileName: { color: palette.text, fontSize: 20, fontWeight: "900" },
  profileMail: { color: palette.muted },
  accountRow: { padding: 16, borderRadius: 20, backgroundColor: palette.panel, borderWidth: 1, borderColor: palette.border, gap: 8 },
  accountTitle: { color: palette.text, fontSize: 16, fontWeight: "800" },
  accountDetail: { color: palette.muted, lineHeight: 20 },
  profileMovieList: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  profileMovieChip: { paddingHorizontal: 12, paddingVertical: 10, borderRadius: 999, backgroundColor: palette.panelSoft, borderWidth: 1, borderColor: palette.border, flexDirection: "row", alignItems: "center", gap: 8 },
  profileMovieChipText: { color: palette.text, fontSize: 12, fontWeight: "700" },
  activityRow: { paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: "rgba(255,255,255,0.05)", gap: 4 },
  activityTitle: { color: palette.text, fontSize: 14, fontWeight: "800" },
  activityMeta: { color: palette.muted, fontSize: 12, lineHeight: 18 },
  activityTime: { color: palette.cyan, fontSize: 11, fontWeight: "700" },
  input: { borderRadius: 16, backgroundColor: palette.panelSoft, borderWidth: 1, borderColor: palette.border, color: palette.text, paddingHorizontal: 14, paddingVertical: 12 },

  backLink: { color: palette.cyan, fontSize: 13, fontWeight: "800" },
  detailHeaderRow: { flexDirection: "row", alignItems: "flex-start", gap: 16, marginBottom: 2 },
  detailThumbWrap: { width: 88, height: 128, borderRadius: 16, overflow: "hidden", borderWidth: 1, borderColor: palette.border, backgroundColor: palette.panel },
  detailThumbImage: { width: "100%", height: "100%" },
  detailHeaderMeta: { flex: 1, gap: 8, paddingTop: 4 },
  detailHeaderTitle: { color: palette.text, fontSize: 26, lineHeight: 30, fontWeight: "900" },
  detailHeaderChips: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  detailHeaderChip: { color: "#fff4ef", fontSize: 11, fontWeight: "800", paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, backgroundColor: "rgba(195,13,18,0.22)" },
  detailHeaderChipSecondary: { color: palette.cyan, fontSize: 11, fontWeight: "800", paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, backgroundColor: "rgba(115,246,221,0.1)", borderWidth: 1, borderColor: "rgba(115,246,221,0.2)" },
  detailHeaderSubline: { color: palette.muted, fontSize: 12, lineHeight: 18 },
  detailPoster: { height: 254, borderRadius: 24, justifyContent: "space-between", padding: 16, overflow: "hidden" },
  detailPosterImage: { ...StyleSheet.absoluteFillObject, opacity: 0.36 },
  detailPosterScrim: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(10,10,15,0.24)" },
  detailOverlayMeta: { position: "absolute", top: 18, right: 18, gap: 8 },
  detailOverlayText: { color: "#fff4ee", fontSize: 11, fontWeight: "800", backgroundColor: "rgba(10,10,15,0.38)", borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6 },
  detailMediaBottom: { zIndex: 1, gap: 12, marginTop: "auto" },
  detailMediaPlay: { alignSelf: "flex-start", flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 14, paddingVertical: 10, borderRadius: 999, backgroundColor: "rgba(7,7,10,0.56)", borderWidth: 1, borderColor: "rgba(255,255,255,0.1)" },
  detailMediaPlayText: { color: palette.text, fontSize: 11, fontWeight: "900", letterSpacing: 1.1 },
  detailMediaFacts: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 8 },
  detailMediaFactText: { color: "#f6ede8", fontSize: 12, fontWeight: "800" },
  detailMediaFactDivider: { color: "rgba(255,255,255,0.55)", fontSize: 12, fontWeight: "800" },
  detailTitle: { color: palette.text, fontSize: 27, lineHeight: 33, fontWeight: "900" },
  detailMeta: { color: palette.cyan, fontSize: 13, fontWeight: "700" },
  detailDescription: { color: palette.muted, lineHeight: 22, fontSize: 15 },
  detailActionsRow: { flexDirection: "row", gap: 10, flexWrap: "wrap" },
  dateMiniRow: { gap: 12, paddingRight: 12 },
  dateMiniCard: { width: 82, minHeight: 94, borderRadius: 20, paddingVertical: 12, paddingHorizontal: 10, alignItems: "center", justifyContent: "center", gap: 4, backgroundColor: palette.panelSoft, borderWidth: 1, borderColor: palette.border },
  dateMiniCardActive: { backgroundColor: "rgba(195,13,18,0.9)", borderColor: "rgba(255,228,220,0.22)", shadowColor: palette.red, shadowOpacity: 0.22, shadowRadius: 12, shadowOffset: { width: 0, height: 6 } },
  dateMiniLabel: { color: "#ffb1ab", fontSize: 10, fontWeight: "900" },
  dateMiniLabelActive: { color: "#fff6f0" },
  dateMiniWeekday: { color: palette.muted, fontSize: 11, fontWeight: "800", textTransform: "uppercase" },
  dateMiniDay: { color: palette.text, fontSize: 24, fontWeight: "900" },
  dateMiniMonth: { color: "#d1c8d1", fontSize: 11, fontWeight: "700" },
  dateMiniTextActive: { color: "#fff6f0" },
  listToggleButton: { minWidth: 156, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, paddingHorizontal: 16, paddingVertical: 13, borderRadius: 18, borderWidth: 1 },
  listToggleButtonFavoriteOn: { backgroundColor: "rgba(201,63,98,0.9)", borderColor: "rgba(255,214,227,0.22)" },
  listToggleButtonFavoriteOff: { backgroundColor: "rgba(72,17,27,0.48)", borderColor: "rgba(201,63,98,0.44)" },
  listToggleButtonWatchlistOn: { backgroundColor: "rgba(18,122,92,0.88)", borderColor: "rgba(198,255,236,0.18)" },
  listToggleButtonWatchlistOff: { backgroundColor: "rgba(11,45,38,0.48)", borderColor: "rgba(115,246,221,0.34)" },
  listToggleButtonText: { fontSize: 13, fontWeight: "900" },
  listToggleButtonTextOn: { color: "#fff6f0" },
  listToggleButtonTextOff: { color: palette.text },
  detailStatsRow: { flexDirection: "row", gap: 10 },
  detailStat: { flex: 1, padding: 16, borderRadius: 18, backgroundColor: palette.panelSoft, borderWidth: 1, borderColor: palette.border },
  detailStatLabel: { color: palette.muted, fontSize: 11, fontWeight: "700" },
  detailStatValue: { color: palette.text, fontSize: 15, fontWeight: "900", marginTop: 6 },
  showtimeGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  showtimeGroupSection: { gap: 12 },
  showtimeGroupHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  showtimeGroupTitle: { color: palette.text, fontSize: 18, fontWeight: "900" },
  showtimeGroupMeta: { color: palette.muted, fontSize: 12, fontWeight: "800" },
  showtimeCard: { width: "48%", backgroundColor: palette.panel, borderRadius: 18, padding: 14, borderWidth: 1, borderColor: palette.border, gap: 6 },
  showtimeCardActive: { borderColor: "rgba(195,13,18,0.42)", backgroundColor: "#1b0f12", shadowColor: palette.red, shadowOpacity: 0.16, shadowRadius: 12, shadowOffset: { width: 0, height: 6 }, elevation: 8 },
  showtimeCardDisabled: { backgroundColor: "rgba(17,17,22,0.74)", borderColor: "rgba(255,255,255,0.04)", opacity: 0.62 },
  showtimePillRow: { flexDirection: "row", gap: 8, flexWrap: "wrap" },
  showtimePill: { color: "#fff4ef", fontSize: 10, fontWeight: "800", paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, backgroundColor: "rgba(195,13,18,0.2)" },
  showtimePillActive: { backgroundColor: "rgba(195,13,18,0.34)" },
  showtimePillDisabled: { color: "#b7a9aa", backgroundColor: "rgba(255,255,255,0.08)" },
  showtimePillSecondary: { color: palette.cyan, fontSize: 10, fontWeight: "800", paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, backgroundColor: "rgba(115,246,221,0.09)", borderWidth: 1, borderColor: "rgba(115,246,221,0.18)" },
  showtimePillSecondaryDisabled: { color: "#9b9aa5", borderColor: "rgba(255,255,255,0.06)", backgroundColor: "rgba(255,255,255,0.04)" },
  showtimeTime: { color: palette.text, fontSize: 20, fontWeight: "900" },
  showtimeTimeDisabled: { color: "#b4adb5" },
  showtimeCinema: { color: palette.text, fontSize: 13, fontWeight: "800" },
  showtimeCinemaDisabled: { color: "#bab4bb" },
  showtimeInfo: { color: palette.muted, fontSize: 12, lineHeight: 18 },
  showtimeMetaStack: { gap: 2, marginTop: 6 },
  showtimeSeatsMetaRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 8, flexWrap: "wrap" },
  showtimeSeatsLeft: { color: "#bdeee3", fontSize: 11, fontWeight: "800" },
  showtimeSeatsLeftDisabled: { color: "#aca3ac" },
  showtimeSeatLevel: { fontSize: 10, fontWeight: "900", paddingHorizontal: 8, paddingVertical: 5, borderRadius: 999, borderWidth: 1 },
  showtimeSeatLevelGood: { color: "#dffff5", backgroundColor: "rgba(31,146,108,0.22)", borderColor: "rgba(115,246,221,0.28)" },
  showtimeSeatLevelWarning: { color: "#fff0cd", backgroundColor: "rgba(255,184,72,0.18)", borderColor: "rgba(255,207,106,0.28)" },
  showtimeSeatLevelCritical: { color: "#ffd9d9", backgroundColor: "rgba(195,13,18,0.18)", borderColor: "rgba(255,126,126,0.22)" },
  showtimeSeatLevelDisabled: { color: "#b0a6ad", backgroundColor: "rgba(255,255,255,0.05)", borderColor: "rgba(255,255,255,0.06)" },
  showtimeFooterRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 6, gap: 8 },
  showtimePrice: { color: palette.amber, fontSize: 13, fontWeight: "900", marginTop: 8 },
  showtimePriceDisabled: { color: "#b9ac89" },
  showtimeLoadingWrap: { minWidth: 40, minHeight: 28, alignItems: "center", justifyContent: "center" },
  showtimeState: { color: palette.text, fontSize: 10, fontWeight: "800", paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, backgroundColor: "rgba(255,255,255,0.06)" },
  showtimeStateActive: { color: "#fff1ed", backgroundColor: "rgba(195,13,18,0.24)" },
  showtimeStateSoon: { color: "#fff3d5", backgroundColor: "rgba(255,184,72,0.22)" },
  showtimeStateBoarding: { color: "#ebfffb", backgroundColor: "rgba(115,246,221,0.22)" },
  showtimeStateDisabled: { color: "#b0a6ad", backgroundColor: "rgba(255,255,255,0.05)" },

  screenShell: { flex: 1 },
  stickyScrollContent: { paddingBottom: 176 },
  seatHeader: { gap: 6 },
  seatPriceRow: { flexDirection: "row", gap: 10, flexWrap: "wrap" },
  seatPriceCard: { width: "48%", padding: 14, borderRadius: 18, backgroundColor: palette.panelSoft, borderWidth: 1, borderColor: palette.border },
  seatPriceLabel: { color: palette.muted, fontSize: 11, fontWeight: "700" },
  seatPriceValue: { color: palette.text, fontSize: 15, fontWeight: "900", marginTop: 6 },
  screenArcWrap: { alignItems: "center", gap: 10 },
  screenArcGlow: { width: "84%", height: 8, borderRadius: 999, backgroundColor: "rgba(115,246,221,0.38)" },
  screenArcText: { color: palette.cyan, fontSize: 11, fontWeight: "800", letterSpacing: 2.5 },
  seatGridWrap: { backgroundColor: palette.panel, borderRadius: 28, paddingVertical: 18, paddingHorizontal: 10, borderWidth: 1, borderColor: palette.border, gap: 12 },
  seatSection: { gap: 10, alignSelf: "center" },
  seatSectionVip: { gap: 10, paddingVertical: 14, paddingHorizontal: 8, borderRadius: 22, backgroundColor: "rgba(255,207,106,0.05)", borderWidth: 1, borderColor: "rgba(255,207,106,0.14)" },
  seatSectionCouple: { gap: 10, paddingVertical: 14, paddingHorizontal: 8, borderRadius: 22, backgroundColor: "rgba(201,63,98,0.06)", borderWidth: 1, borderColor: "rgba(201,63,98,0.18)" },
  seatSectionLabel: { alignSelf: "center", color: palette.muted, fontSize: 10, fontWeight: "800", letterSpacing: 2 },
  seatSectionLabelVip: { alignSelf: "center", color: palette.amber, fontSize: 10, fontWeight: "800", letterSpacing: 2 },
  seatSectionLabelCouple: { alignSelf: "center", color: "#ff89a8", fontSize: 10, fontWeight: "800", letterSpacing: 2 },
  seatRow: { flexDirection: "row", justifyContent: "center", alignItems: "center", gap: 8 },
  seatRowRail: { width: 28, alignItems: "center", justifyContent: "center", alignSelf: "stretch" },
  seatRowRailMirror: { width: 28 },
  seatRowContent: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 0, flexGrow: 0, flexShrink: 1 },
  seatColumnRow: { flexDirection: "row", justifyContent: "center", alignItems: "center", gap: 8, paddingBottom: 6 },
  seatColumnRowBottom: { paddingTop: 6, paddingBottom: 0, opacity: 0.7 },
  seatColumnSideLabel: { color: "rgba(255,255,255,0.32)", fontSize: 8, textAlign: "center", fontWeight: "900", letterSpacing: 1.2 },
  seatColumnGroup: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 4 },
  seatColumnLabel: { width: 34, color: "rgba(255,255,255,0.44)", fontSize: 10, textAlign: "center", fontWeight: "800" },
  seatColumnLabelHot: { color: "#9ff4df" },
  seatRowLabel: { color: palette.muted, fontSize: 11, textAlign: "center", fontWeight: "900", letterSpacing: 0.6 },
  seatRowLabelVip: { color: palette.amber },
  seatRowLabelCouple: { color: "#ff89a8" },
  seatAisleGap: { width: 10 },
  seatOuterAisle: { width: 22 },
  seatOuterAisleLine: { width: 22, alignItems: "center", justifyContent: "space-between", alignSelf: "stretch", paddingVertical: 2 },
  seatAisleCurveTop: { width: 1.5, flex: 1, maxHeight: 22, backgroundColor: "rgba(255,255,255,0.14)", borderRadius: 999 },
  seatAisleCurveTopLeft: { transform: [{ translateX: 4 }, { rotate: "12deg" }] },
  seatAisleCurveTopRight: { transform: [{ translateX: -4 }, { rotate: "-12deg" }] },
  seatAisleCurveBottom: { width: 1.5, flex: 1, backgroundColor: "rgba(255,255,255,0.08)", borderRadius: 999 },
  seatGroup: { flexDirection: "row", alignItems: "flex-start", justifyContent: "center", gap: 4 },
  seatGroupPlaceholder: { width: 24 },
  seatCell: { width: 34, alignItems: "center", justifyContent: "flex-start", gap: 4, paddingVertical: 2, position: "relative" },
  coupleSeatCell: { width: 62 },
  seatDisabled: { opacity: 0.72 },
  seatPulseRing: { position: "absolute", top: -4, left: -4, right: -4, bottom: -4, borderRadius: 14, borderWidth: 1.5, borderColor: "rgba(255,255,255,0.92)", backgroundColor: "rgba(255,255,255,0.08)" },
  seatPulseRingCouple: { borderRadius: 18 },
  seatShell: {
    width: 28,
    height: 28,
    alignItems: "center",
    justifyContent: "flex-start",
    borderWidth: 1.5,
    borderRadius: 10,
    paddingTop: 3,
    backgroundColor: "rgba(10,10,14,0.36)",
    shadowOpacity: 0.12,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
  },
  seatShellVip: { backgroundColor: "rgba(255,207,106,0.08)" },
  seatShellCouple: { width: 56, height: 30, borderRadius: 14, paddingTop: 4 },
  seatShellHot: { backgroundColor: "rgba(127,228,201,0.12)" },
  seatHotEdgeTop: { borderTopWidth: 2.5 },
  seatHotEdgeBottom: { borderBottomWidth: 2.5 },
  seatHotEdgeLeft: { borderLeftWidth: 2.5 },
  seatHotEdgeRight: { borderRightWidth: 2.5 },
  seatHotOutline: { borderLeftWidth: 2.5, borderRightWidth: 2.5, borderColor: "rgba(127,228,201,0.95)", borderRadius: 0, paddingHorizontal: 4, marginHorizontal: 2, backgroundColor: "rgba(127,228,201,0.06)", overflow: "visible", shadowColor: "#7fe4c9", shadowOpacity: 0.12, shadowRadius: 14, shadowOffset: { width: 0, height: 0 } },
  seatHotOutlineTop: { borderTopWidth: 2.5, borderTopLeftRadius: 16, borderTopRightRadius: 16, paddingTop: 4 },
  seatHotOutlineBottom: { borderBottomWidth: 2.5, borderBottomLeftRadius: 16, borderBottomRightRadius: 16, paddingBottom: 4 },
  seatHotOutlineSingleRow: { borderRadius: 16 },
  seatHotGlow: { position: "absolute", left: -4, right: -4, top: -4, bottom: -4, borderRadius: 18, backgroundColor: "rgba(127,228,201,0.1)" },
  seatHotZoneLabelWrap: { position: "absolute", top: -10, alignSelf: "center", paddingHorizontal: 10, paddingVertical: 4, borderRadius: 999, backgroundColor: "#7fe4c9", borderWidth: 1, borderColor: "rgba(255,255,255,0.22)", zIndex: 3, shadowColor: "#7fe4c9", shadowOpacity: 0.28, shadowRadius: 10, shadowOffset: { width: 0, height: 0 } },
  seatHotZoneLabelWrapBottom: { top: undefined, bottom: -10 },
  seatHotZoneLabel: { color: "#06251d", fontSize: 10, fontWeight: "900", letterSpacing: 0.8 },
  seatShellActive: {
    backgroundColor: "rgba(255,255,255,0.18)",
    borderColor: "#fff7f0",
    shadowColor: "#ffffff",
    shadowOpacity: 0.34,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    transform: [{ scale: 1.08 }],
  },
  seatShellDisabled: { backgroundColor: "rgba(255,255,255,0.04)", borderColor: "rgba(255,255,255,0.08)", shadowOpacity: 0 },
  seatBack: { width: 16, height: 9, borderRadius: 6, marginBottom: 2 },
  seatBackCouple: { width: 38, height: 10, borderRadius: 7 },
  seatArmRow: { flexDirection: "row", alignItems: "center", gap: 2 },
  seatArm: { width: 3, height: 9, borderRadius: 999 },
  seatCushion: { width: 14, height: 8, borderRadius: 4 },
  seatCushionCouple: { width: 32, height: 9, borderRadius: 5 },
  seatLeg: { width: 10, height: 3, borderRadius: 999, marginTop: 2 },
  seatCellText: { color: "#d8d1c7", fontSize: 8, fontWeight: "900" },
  seatCellTextActive: { color: "#ffffff", textShadowColor: "rgba(255,255,255,0.6)", textShadowRadius: 6, textShadowOffset: { width: 0, height: 0 } },
  seatCellTextDisabled: { color: "#8f8790" },
  seatActive: { transform: [{ scale: 1.02 }] },
  legendGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  legendItem: { flexDirection: "row", alignItems: "center", gap: 8, backgroundColor: palette.panelSoft, paddingHorizontal: 12, paddingVertical: 10, borderRadius: 999 },
  legendDot: { width: 12, height: 12, borderRadius: 999 },
  legendDotSelected: { borderWidth: 2, borderColor: "rgba(255,179,102,0.95)", shadowColor: "#ffffff", shadowOpacity: 0.28, shadowRadius: 8, shadowOffset: { width: 0, height: 0 } },
  legendText: { color: palette.text, fontSize: 12, fontWeight: "700" },
  seatHotBadge: { alignSelf: "center", flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999, backgroundColor: "rgba(127,228,201,0.9)", borderWidth: 1, borderColor: "rgba(228,255,248,0.26)" },
  seatHotBadgeText: { color: "#06251d", fontSize: 11, fontWeight: "900" },
  seatInlineHint: { position: "absolute", bottom: "100%", marginBottom: 6, minWidth: 74, paddingHorizontal: 8, paddingVertical: 6, borderRadius: 12, backgroundColor: "rgba(18,18,24,0.96)", borderWidth: 1, borderColor: "rgba(255,255,255,0.14)", alignItems: "center", zIndex: 4 },
  seatInlineHintCouple: { minWidth: 110 },
  seatInlineHintPrice: { color: palette.amber, fontSize: 11, fontWeight: "900" },
  seatInlineHintMeta: { color: "#d5cbd3", fontSize: 9, fontWeight: "800", textAlign: "center" },
  bottomSummary: { flexDirection: "row", justifyContent: "space-between", padding: 18, borderRadius: 22, backgroundColor: palette.panelStrong, borderWidth: 1, borderColor: "rgba(195,13,18,0.16)" },
  stickyFooterWrap: { position: "absolute", left: 0, right: 0, bottom: 0, paddingHorizontal: 18, paddingBottom: 16, paddingTop: 14, backgroundColor: "rgba(5,5,7,0.38)" },
  stickyFooterTopGlow: { position: "absolute", top: 4, left: 28, right: 28, height: 22, borderRadius: 999, opacity: 0.95, zIndex: 2 },
  stickyFooter: { overflow: "hidden", borderRadius: 26, padding: 16, backgroundColor: "rgba(20,12,15,0.72)", borderWidth: 1, borderColor: "rgba(255,255,255,0.12)", flexDirection: "row", gap: 14, alignItems: "center", shadowColor: "#000", shadowOpacity: 0.32, shadowRadius: 16, shadowOffset: { width: 0, height: -6 }, elevation: 18 },
  stickyFooterInnerHighlight: { position: "absolute", top: 1, left: 14, right: 14, height: 1, borderRadius: 999, backgroundColor: "rgba(255,255,255,0.18)" },
  stickyFooterNoise: { ...StyleSheet.absoluteFillObject },
  stickyFooterNoiseDot: { position: "absolute", borderRadius: 999, backgroundColor: "rgba(255,255,255,0.95)" },
  stickyFooterNoiseDotDark: { position: "absolute", borderRadius: 999, backgroundColor: "rgba(8,9,12,0.86)" },
  stickySummaryMain: { flex: 1, gap: 4 },
  stickyPrimaryValue: { color: palette.text, fontSize: 18, fontWeight: "900" },
  stickySecondaryValue: { color: palette.muted, fontSize: 12, lineHeight: 18 },
  stickyActionBlock: { minWidth: 148, alignItems: "stretch", gap: 8 },
  summaryLabel: { color: palette.muted, fontSize: 12, fontWeight: "700" },
  summaryValue: { color: palette.text, fontSize: 18, fontWeight: "900", marginTop: 4 },
  trailerModalBackdrop: { flex: 1, backgroundColor: "rgba(5,5,7,0.82)", justifyContent: "center", padding: 18 },
  trailerModalShell: { overflow: "hidden", borderRadius: 28, backgroundColor: "rgba(12,12,16,0.96)", borderWidth: 1, borderColor: "rgba(255,255,255,0.1)", padding: 16, gap: 14 },
  trailerModalStroke: { ...StyleSheet.absoluteFillObject, opacity: 0.6 },
  trailerModalHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 12, zIndex: 1 },
  trailerCloseButton: { width: 38, height: 38, borderRadius: 999, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(255,255,255,0.08)", borderWidth: 1, borderColor: "rgba(255,255,255,0.1)" },
  trailerPosterPreview: { zIndex: 1, height: 260, borderRadius: 22, overflow: "hidden", justifyContent: "flex-end", backgroundColor: "#111111", borderWidth: 1, borderColor: "rgba(255,255,255,0.08)" },
  trailerPosterImage: { ...StyleSheet.absoluteFillObject },
  trailerPosterScrim: { ...StyleSheet.absoluteFillObject },
  trailerPosterCenter: { alignItems: "center", justifyContent: "center", padding: 24, gap: 10 },
  trailerPosterPlay: { width: 64, height: 64, borderRadius: 999, alignItems: "center", justifyContent: "center", backgroundColor: "rgba(195,13,18,0.86)", borderWidth: 1, borderColor: "rgba(255,255,255,0.24)", shadowColor: palette.red, shadowOpacity: 0.36, shadowRadius: 18, shadowOffset: { width: 0, height: 8 } },
  trailerPosterTitle: { color: palette.text, fontSize: 18, fontWeight: "900", textAlign: "center" },
  trailerPosterHint: { color: "#e8ddd7", fontSize: 12, fontWeight: "700" },
  trailerPlayerWrap: { zIndex: 1, height: 260, borderRadius: 22, overflow: "hidden", backgroundColor: "#000000", borderWidth: 1, borderColor: "rgba(255,255,255,0.08)" },
  trailerWebview: { flex: 1, backgroundColor: "#000000" },
  trailerLoadingOverlay: { ...StyleSheet.absoluteFillObject, alignItems: "center", justifyContent: "center", gap: 10, backgroundColor: "rgba(5,5,7,0.58)" },
  trailerLoadingText: { color: "#f4eee8", fontSize: 12, fontWeight: "800" },

  comboCard: { flexDirection: "row", justifyContent: "space-between", gap: 12, padding: 18, borderRadius: 22, backgroundColor: palette.panel, borderWidth: 1, borderColor: palette.border },
  comboCardActive: { borderColor: "rgba(115,246,221,0.5)", backgroundColor: "#10211d" },
  comboInfo: { flex: 1, gap: 4 },
  comboTitle: { color: palette.text, fontSize: 16, fontWeight: "800" },
  comboDetail: { color: palette.muted, lineHeight: 20 },
  comboPrice: { color: palette.amber, fontWeight: "900", alignSelf: "center" },
  paymentWrap: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  paymentMethod: { paddingHorizontal: 16, paddingVertical: 11, borderRadius: 999, backgroundColor: palette.panelSoft, borderWidth: 1, borderColor: "rgba(115,246,221,0.18)" },
  paymentMethodActive: { backgroundColor: "rgba(115,246,221,0.13)", borderColor: "rgba(115,246,221,0.7)" },
  paymentMethodText: { color: palette.cyan, fontWeight: "800" },
  paymentMethodTextActive: { color: "#ebfffb" },
  checkoutCard: { backgroundColor: palette.panelStrong, borderRadius: 24, padding: 20, gap: 8, borderWidth: 1, borderColor: "rgba(195,13,18,0.18)" },
  checkoutSummaryGrid: { flexDirection: "row", gap: 10 },
  checkoutSummaryCell: { flex: 1, padding: 16, borderRadius: 18, backgroundColor: palette.panelSoft, borderWidth: 1, borderColor: palette.border },
  checkoutPrice: { color: palette.text, fontSize: 30, fontWeight: "900" },
  checkoutHint: { color: palette.muted, lineHeight: 20 },
  ticketDetailHero: { padding: 22, borderRadius: 26, backgroundColor: palette.panelStrong, borderWidth: 1, borderColor: "rgba(195,13,18,0.18)", gap: 8 },
  ticketDetailGrid: { flexDirection: "row", gap: 10 },
  aiCompactScrollContent: { paddingBottom: 120 },
  aiChatWrap: { gap: 10 },
  aiMessageStack: { gap: 10 },
  aiMessageBubble: { borderRadius: 16, borderWidth: 1, padding: 12, gap: 8 },
  aiMessageBubbleUser: { backgroundColor: "rgba(115,246,221,0.1)", borderColor: "rgba(115,246,221,0.26)" },
  aiMessageBubbleAssistant: { backgroundColor: palette.panel, borderColor: palette.border },
  aiMessageRole: { color: palette.cyan, fontSize: 11, fontWeight: "800", letterSpacing: 0.6 },
  aiMessageText: { color: palette.text, fontSize: 13, lineHeight: 20 },
  aiSuggestionStack: { gap: 8 },
  aiSuggestionCard: { borderRadius: 14, borderWidth: 1, borderColor: "rgba(255,255,255,0.09)", backgroundColor: "rgba(255,255,255,0.03)", padding: 10, gap: 4 },
  aiSuggestionTitle: { color: "#fff4ef", fontSize: 14, fontWeight: "900" },
  aiSuggestionMeta: { color: "#d2c8d0", fontSize: 12, fontWeight: "700" },
  aiSuggestionReason: { color: palette.muted, fontSize: 12, lineHeight: 18 },
  aiInput: { minHeight: 88, textAlignVertical: "top" },
  aiFab: {
    position: "absolute",
    width: 58,
    height: 58,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(195,13,18,0.96)",
    borderWidth: 1,
    borderColor: "rgba(255,241,236,0.24)",
    zIndex: 46,
    elevation: 24,
    shadowColor: palette.red,
    shadowOpacity: 0.42,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
  },
  aiFabLabel: { color: "#fff9f6", fontSize: 9, fontWeight: "900", letterSpacing: 0.7 },
  aiMiniPanel: {
    position: "absolute",
    left: 12,
    right: 12,
    bottom: 102,
    maxHeight: "72%",
    borderRadius: 22,
    backgroundColor: "rgba(13,13,19,0.97)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
    overflow: "hidden",
    zIndex: 45,
    elevation: 22,
    shadowColor: "#000",
    shadowOpacity: 0.34,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
  },
  aiMiniHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.08)",
  },
  aiMiniTitle: { color: "#fff5f1", fontSize: 14, fontWeight: "900" },

  bottomBar: {
    position: "absolute",
    left: 10,
    right: 10,
    bottom: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    overflow: "hidden",
    backgroundColor: "rgba(15,15,20,0.62)",
    borderRadius: 28,
    paddingVertical: 11,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.16)",
    minHeight: 84,
    zIndex: 30,
    elevation: 20,
    shadowColor: "#000",
    shadowOpacity: 0.32,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
  },
  tabPressable: {
    flex: 1,
    zIndex: 2,
  },
  tabItem: {
    minWidth: 0,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    paddingHorizontal: 4,
    borderRadius: 20,
    minHeight: 60,
    gap: 4,
  },
  tabItemGlow: {
    position: "absolute",
    left: 12,
    top: 12,
    bottom: 12,
    borderRadius: 20,
    backgroundColor: "rgba(195,13,18,0.28)",
    shadowColor: palette.red,
    shadowOpacity: 0.52,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 10 },
    elevation: 10,
  },
  tabItemActive: {
    position: "absolute",
    left: 12,
    top: 11,
    bottom: 11,
    borderRadius: 20,
    backgroundColor: palette.red,
    borderWidth: 1,
    borderColor: "rgba(255,240,236,0.24)",
    shadowColor: palette.red,
    shadowOpacity: 0.38,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 14,
  },
  tabIcon: { color: "#766f7d" },
  tabIconActive: { color: palette.text },
  tabText: { color: "#766f7d", fontSize: 10, fontWeight: "800", letterSpacing: 0.1 },
  tabTextActive: { color: palette.text },
});
