import { StyleSheet } from "react-native";

export const palette = {
  bg: "#050507",
  bgSoft: "#0d0d12",
  panel: "#111116",
  panelSoft: "#17171f",
  panelStrong: "#1c0f12",
  text: "#f4eee8",
  muted: "#9d96a3",
  red: "#c30d12",
  redSoft: "#6a1118",
  cyan: "#73f6dd",
  amber: "#ffcf6a",
  border: "rgba(255,255,255,0.08)",
  sold: "#494855",
  held: "#5e6a80",
  seat: "#e9e2d8",
  vip: "#ffcf6a",
  couple: "#c93f62",
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: palette.bg },
  topBar: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(195,13,18,0.18)",
    backgroundColor: "#0b0b10",
  },
  brand: { color: palette.red, fontSize: 16, fontWeight: "900", letterSpacing: 1.4 },
  avatarMini: { width: 34, height: 34, borderRadius: 999, borderWidth: 1, borderColor: "rgba(195,13,18,0.5)", backgroundColor: "#231116" },
  scrollContent: { paddingHorizontal: 20, paddingTop: 20, paddingBottom: 148, gap: 20 },
  toast: {
    position: "absolute",
    top: 10,
    alignSelf: "center",
    minWidth: 168,
    maxWidth: "88%",
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "rgba(10,10,14,0.96)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    zIndex: 40,
    shadowColor: "#000",
    shadowOpacity: 0.32,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 16,
  },
  toastSuccess: { borderColor: "rgba(115,246,221,0.48)", backgroundColor: "rgba(5,36,31,0.98)" },
  toastError: { borderColor: "rgba(255,107,107,0.46)", backgroundColor: "rgba(52,10,15,0.98)" },
  toastIconWrap: { width: 36, height: 36, borderRadius: 999, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "rgba(255,255,255,0.08)" },
  toastIconWrapSuccess: { borderColor: "rgba(138,255,234,0.34)", shadowColor: palette.cyan, shadowOpacity: 0.24, shadowRadius: 10, shadowOffset: { width: 0, height: 4 } },
  toastIconWrapError: { borderColor: "rgba(255,141,141,0.3)", shadowColor: "#ff6b6b", shadowOpacity: 0.22, shadowRadius: 10, shadowOffset: { width: 0, height: 4 } },
  toastBody: { flexShrink: 1, gap: 3, paddingRight: 8 },
  toastHeader: { flexDirection: "row", alignItems: "center", gap: 6 },
  toastDot: { width: 8, height: 8, borderRadius: 999, backgroundColor: palette.amber },
  toastDotSuccess: { backgroundColor: palette.cyan },
  toastDotError: { backgroundColor: "#ff6b6b" },
  toastLabel: { color: palette.text, fontSize: 11, fontWeight: "900", letterSpacing: 0.4 },
  toastTone: { color: palette.muted, fontSize: 10, fontWeight: "800", letterSpacing: 0.4 },
  toastToneSuccess: { color: "#8affea" },
  toastToneError: { color: "#ff9a9a" },
  toastText: { color: palette.text, fontWeight: "700", lineHeight: 17, fontSize: 12, flexShrink: 1 },
  skeletonBlock: { borderRadius: 24, backgroundColor: palette.panel, borderWidth: 1, borderColor: palette.border },

  heroCard: { minHeight: 420, borderRadius: 30, padding: 24, justifyContent: "space-between", overflow: "hidden", borderWidth: 1, borderColor: "rgba(195,13,18,0.18)" },
  heroImage: { ...StyleSheet.absoluteFillObject, opacity: 0.32 },
  heroOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(7,7,10,0.46)" },
  heroTopLine: { zIndex: 1, flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  eyebrow: { color: palette.amber, fontSize: 11, fontWeight: "800", letterSpacing: 1.4 },
  heroTag: { color: "#fff5ef", fontSize: 12, fontWeight: "800", paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, backgroundColor: "rgba(195,13,18,0.22)" },
  heroContent: { zIndex: 1, gap: 8, marginTop: 44 },
  heroKicker: { color: "#ffe0d9", fontSize: 12, fontWeight: "800", letterSpacing: 1.6 },
  heroTitle: { color: palette.text, fontSize: 40, lineHeight: 44, fontWeight: "900" },
  heroSubline: { color: "#efe5df", fontSize: 13, fontWeight: "700" },
  heroBody: { color: "#ddd3cc", fontSize: 15, lineHeight: 22, maxWidth: 280 },
  heroMetrics: { zIndex: 1, flexDirection: "row", gap: 10 },
  metricItem: { flex: 1, borderRadius: 16, padding: 14, backgroundColor: "rgba(8,8,12,0.45)", borderWidth: 1, borderColor: "rgba(255,255,255,0.08)" },
  metricLabel: { color: "#c6bec6", fontSize: 11, fontWeight: "700" },
  metricValue: { color: "#fff", fontSize: 15, fontWeight: "900", marginTop: 6 },
  heroActions: { zIndex: 1, flexDirection: "row", gap: 10, marginTop: 8 },

  quickStrip: { flexDirection: "row", gap: 10 },
  quickStripItem: { flex: 1, padding: 16, borderRadius: 18, backgroundColor: palette.panel, borderWidth: 1, borderColor: palette.border },
  quickStripLabel: { color: palette.muted, fontSize: 11, fontWeight: "700" },
  quickStripValue: { color: palette.text, fontSize: 15, fontWeight: "900", marginTop: 6 },

  button: { paddingHorizontal: 18, paddingVertical: 13, borderRadius: 999, alignItems: "center", justifyContent: "center" },
  buttonPrimary: { backgroundColor: palette.red },
  buttonSecondary: { borderWidth: 1, borderColor: "rgba(255,255,255,0.18)", backgroundColor: "rgba(7,7,10,0.24)" },
  buttonText: { fontSize: 13, fontWeight: "800" },
  buttonTextPrimary: { color: "#fff8f6" },
  buttonTextSecondary: { color: palette.text },

  sectionHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  sectionTitle: { color: palette.text, fontSize: 24, fontWeight: "900" },
  sectionAction: { color: palette.amber, fontSize: 12, fontWeight: "800" },
  row: { gap: 14, paddingRight: 12 },

  bannerCard: { minHeight: 152, borderRadius: 24, padding: 20, justifyContent: "flex-end", overflow: "hidden" },
  bannerImage: { borderRadius: 24, opacity: 0.24 },
  bannerOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(10,10,15,0.3)" },
  bannerEyebrow: { color: "#f4d7d1", fontSize: 11, fontWeight: "800", letterSpacing: 0.8 },
  bannerTitle: { color: "#fff", fontSize: 28, fontWeight: "900", marginTop: 8 },
  bannerText: { color: "#efe6e4", fontSize: 14, lineHeight: 20, marginTop: 8, maxWidth: 280 },

  movieCard: { width: 176, gap: 10 },
  poster: { height: 238, borderRadius: 22, justifyContent: "space-between", padding: 14, overflow: "hidden" },
  posterImage: { borderRadius: 22 },
  posterScrim: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(10,10,15,0.18)" },
  posterBadge: { color: "#fff", fontSize: 11, fontWeight: "800", paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, backgroundColor: "rgba(9,9,12,0.52)", alignSelf: "flex-start" },
  movieTitle: { color: palette.text, fontSize: 17, fontWeight: "800" },
  movieMeta: { color: palette.muted, fontSize: 12, lineHeight: 18 },
  movieFooter: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  movieScore: { color: palette.amber, fontWeight: "900", fontSize: 12 },
  movieAction: { color: palette.text, fontWeight: "700", fontSize: 12 },

  rankingWrap: { gap: 12 },
  rankingRow: { flexDirection: "row", alignItems: "center", gap: 14, padding: 14, borderRadius: 20, backgroundColor: palette.panel, borderWidth: 1, borderColor: palette.border },
  rankPoster: { width: 42, height: 56, borderRadius: 12 },
  rankMain: { flex: 1, gap: 4 },
  rankMovie: { color: palette.text, fontWeight: "800", fontSize: 16 },
  rankRevenue: { color: palette.muted, fontSize: 12, fontWeight: "700" },
  rankActionText: { color: palette.amber, fontWeight: "800", fontSize: 12 },

  exploreHero: { padding: 20, borderRadius: 24, backgroundColor: palette.panelStrong, borderWidth: 1, borderColor: "rgba(195,13,18,0.18)", gap: 8 },
  exploreCard: { backgroundColor: palette.panel, borderRadius: 24, overflow: "hidden", borderWidth: 1, borderColor: palette.border },
  explorePoster: { height: 196, backgroundColor: palette.panelSoft },
  explorePosterImage: { width: "100%", height: "100%" },
  exploreBody: { padding: 18, gap: 6 },
  exploreBadge: { color: palette.amber, fontSize: 11, fontWeight: "800" },
  exploreTitle: { color: palette.text, fontSize: 22, fontWeight: "900" },
  exploreMeta: { color: palette.cyan, fontSize: 12, fontWeight: "700" },
  exploreDescription: { color: palette.muted, lineHeight: 21 },

  screenIntro: { gap: 8 },
  ticketCard: { backgroundColor: palette.panel, borderRadius: 24, borderWidth: 1, borderColor: palette.border, overflow: "hidden", gap: 8, paddingBottom: 18 },
  ticketEmptyCard: { backgroundColor: palette.panelStrong, borderRadius: 24, borderWidth: 1, borderColor: "rgba(195,13,18,0.18)", padding: 18, gap: 14 },
  ticketEmptyLabel: { color: palette.amber, fontSize: 11, fontWeight: "800", letterSpacing: 1.4 },
  ticketStripe: { height: 5, backgroundColor: palette.red },
  ticketHead: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 10 },
  ticketContent: { paddingHorizontal: 18, paddingTop: 18, gap: 6 },
  ticketMovie: { color: palette.text, fontSize: 18, fontWeight: "900" },
  ticketInfo: { color: palette.muted, lineHeight: 19 },
  ticketStatus: { color: "#f4e0da", fontSize: 11, fontWeight: "800", borderWidth: 1, borderColor: "rgba(255,255,255,0.08)", backgroundColor: "rgba(255,255,255,0.06)", borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6 },
  ticketStatusPaid: { color: "#ddfff7", borderColor: "rgba(115,246,221,0.24)", backgroundColor: "rgba(115,246,221,0.12)" },

  authHero: { padding: 24, borderRadius: 28, backgroundColor: palette.panelStrong, borderWidth: 1, borderColor: "rgba(195,13,18,0.2)", gap: 10 },
  authTitle: { color: palette.text, fontSize: 28, lineHeight: 34, fontWeight: "900" },
  authBody: { color: "#ddd3cc", fontSize: 14, lineHeight: 22 },
  authFeatureRow: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginTop: 4 },
  authFeatureChip: { paddingHorizontal: 12, paddingVertical: 10, borderRadius: 999, backgroundColor: "rgba(255,255,255,0.06)", borderWidth: 1, borderColor: "rgba(255,255,255,0.08)" },
  authFeatureText: { color: palette.text, fontSize: 12, fontWeight: "800" },
  authStepRow: { flexDirection: "row", justifyContent: "center", gap: 8, marginTop: -2 },
  authStepDot: { width: 9, height: 9, borderRadius: 999, backgroundColor: "rgba(255,255,255,0.14)" },
  authStepDotActive: { width: 26, backgroundColor: palette.red },
  authNavRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  authLink: { color: palette.cyan, fontSize: 13, fontWeight: "800" },
  authCard: { padding: 20, borderRadius: 24, backgroundColor: palette.panel, borderWidth: 1, borderColor: palette.border, gap: 10 },
  googleButton: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 10, paddingHorizontal: 18, paddingVertical: 14, borderRadius: 999, backgroundColor: "#1f4fd8", borderWidth: 1, borderColor: "rgba(255,255,255,0.08)" },
  googleButtonText: { color: "#ffffff", fontSize: 13, fontWeight: "900" },
  authDivider: { color: palette.muted, fontSize: 12, fontWeight: "700", textAlign: "center", marginVertical: 2 },

  profileHero: { flexDirection: "row", alignItems: "center", gap: 16, backgroundColor: palette.panelStrong, borderWidth: 1, borderColor: "rgba(195,13,18,0.18)", borderRadius: 26, padding: 20 },
  profileMetaBlock: { flex: 1, gap: 4 },
  avatar: { width: 62, height: 62, borderRadius: 999, backgroundColor: "#2b0e12", borderWidth: 1, borderColor: "rgba(195,13,18,0.4)" },
  profileName: { color: palette.text, fontSize: 20, fontWeight: "900" },
  profileMail: { color: palette.muted },
  accountRow: { padding: 18, borderRadius: 22, backgroundColor: palette.panel, borderWidth: 1, borderColor: palette.border, gap: 8 },
  accountTitle: { color: palette.text, fontSize: 16, fontWeight: "800" },
  accountDetail: { color: palette.muted, lineHeight: 20 },
  profileMovieList: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  profileMovieChip: { paddingHorizontal: 12, paddingVertical: 10, borderRadius: 999, backgroundColor: palette.panelSoft, borderWidth: 1, borderColor: palette.border },
  profileMovieChipText: { color: palette.text, fontSize: 12, fontWeight: "700" },
  activityRow: { paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: "rgba(255,255,255,0.05)", gap: 4 },
  activityTitle: { color: palette.text, fontSize: 14, fontWeight: "800" },
  activityMeta: { color: palette.muted, fontSize: 12, lineHeight: 18 },
  activityTime: { color: palette.cyan, fontSize: 11, fontWeight: "700" },
  input: { borderRadius: 16, backgroundColor: palette.panelSoft, borderWidth: 1, borderColor: palette.border, color: palette.text, paddingHorizontal: 14, paddingVertical: 12 },

  backLink: { color: palette.cyan, fontSize: 13, fontWeight: "800" },
  detailHeaderRow: { flexDirection: "row", alignItems: "flex-start", gap: 16, marginBottom: 2 },
  detailThumbWrap: { width: 88, height: 128, borderRadius: 16, overflow: "hidden", borderWidth: 1, borderColor: palette.border, backgroundColor: palette.panel },
  detailThumbImage: { width: "100%", height: "100%" },
  detailHeaderMeta: { flex: 1, gap: 8, paddingTop: 4 },
  detailHeaderTitle: { color: palette.text, fontSize: 28, lineHeight: 32, fontWeight: "900" },
  detailHeaderChips: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  detailHeaderChip: { color: "#fff4ef", fontSize: 11, fontWeight: "800", paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, backgroundColor: "rgba(195,13,18,0.22)" },
  detailHeaderChipSecondary: { color: palette.cyan, fontSize: 11, fontWeight: "800", paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, backgroundColor: "rgba(115,246,221,0.1)", borderWidth: 1, borderColor: "rgba(115,246,221,0.2)" },
  detailHeaderSubline: { color: palette.muted, fontSize: 12, lineHeight: 18 },
  detailPoster: { height: 270, borderRadius: 28, justifyContent: "space-between", padding: 18, overflow: "hidden" },
  detailPosterImage: { ...StyleSheet.absoluteFillObject, opacity: 0.36 },
  detailPosterScrim: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(10,10,15,0.24)" },
  detailOverlayMeta: { position: "absolute", top: 18, right: 18, gap: 8 },
  detailOverlayText: { color: "#fff4ee", fontSize: 11, fontWeight: "800", backgroundColor: "rgba(10,10,15,0.38)", borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6 },
  detailMediaBottom: { zIndex: 1, gap: 12, marginTop: "auto" },
  detailMediaPlay: { alignSelf: "flex-start", paddingHorizontal: 14, paddingVertical: 10, borderRadius: 999, backgroundColor: "rgba(7,7,10,0.56)", borderWidth: 1, borderColor: "rgba(255,255,255,0.1)" },
  detailMediaPlayText: { color: palette.text, fontSize: 11, fontWeight: "900", letterSpacing: 1.1 },
  detailMediaFacts: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 8 },
  detailMediaFactText: { color: "#f6ede8", fontSize: 12, fontWeight: "800" },
  detailMediaFactDivider: { color: "rgba(255,255,255,0.55)", fontSize: 12, fontWeight: "800" },
  detailTitle: { color: palette.text, fontSize: 30, lineHeight: 36, fontWeight: "900" },
  detailMeta: { color: palette.cyan, fontSize: 13, fontWeight: "700" },
  detailDescription: { color: palette.muted, lineHeight: 22, fontSize: 15 },
  detailActionsRow: { flexDirection: "row", gap: 10, flexWrap: "wrap" },
  detailStatsRow: { flexDirection: "row", gap: 10 },
  detailStat: { flex: 1, padding: 16, borderRadius: 18, backgroundColor: palette.panelSoft, borderWidth: 1, borderColor: palette.border },
  detailStatLabel: { color: palette.muted, fontSize: 11, fontWeight: "700" },
  detailStatValue: { color: palette.text, fontSize: 15, fontWeight: "900", marginTop: 6 },
  showtimeGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  showtimeCard: { width: "47%", backgroundColor: palette.panel, borderRadius: 20, padding: 16, borderWidth: 1, borderColor: palette.border, gap: 6 },
  showtimePillRow: { flexDirection: "row", gap: 8, flexWrap: "wrap" },
  showtimePill: { color: "#fff4ef", fontSize: 10, fontWeight: "800", paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, backgroundColor: "rgba(195,13,18,0.2)" },
  showtimePillSecondary: { color: palette.cyan, fontSize: 10, fontWeight: "800", paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, backgroundColor: "rgba(115,246,221,0.09)", borderWidth: 1, borderColor: "rgba(115,246,221,0.18)" },
  showtimeTime: { color: palette.text, fontSize: 20, fontWeight: "900" },
  showtimeCinema: { color: palette.text, fontSize: 13, fontWeight: "800" },
  showtimeInfo: { color: palette.muted, fontSize: 12, lineHeight: 18 },
  showtimePrice: { color: palette.amber, fontSize: 13, fontWeight: "900", marginTop: 8 },

  screenShell: { flex: 1 },
  stickyScrollContent: { paddingBottom: 176 },
  seatHeader: { gap: 6 },
  seatPriceRow: { flexDirection: "row", gap: 10 },
  seatPriceCard: { flex: 1, padding: 14, borderRadius: 18, backgroundColor: palette.panelSoft, borderWidth: 1, borderColor: palette.border },
  seatPriceLabel: { color: palette.muted, fontSize: 11, fontWeight: "700" },
  seatPriceValue: { color: palette.text, fontSize: 15, fontWeight: "900", marginTop: 6 },
  screenArcWrap: { alignItems: "center", gap: 10 },
  screenArcGlow: { width: "84%", height: 8, borderRadius: 999, backgroundColor: "rgba(115,246,221,0.38)" },
  screenArcText: { color: palette.cyan, fontSize: 11, fontWeight: "800", letterSpacing: 2.5 },
  seatGridWrap: { backgroundColor: palette.panel, borderRadius: 28, paddingVertical: 18, paddingHorizontal: 10, borderWidth: 1, borderColor: palette.border, gap: 10 },
  seatSection: { gap: 10 },
  seatSectionVip: { gap: 10, paddingVertical: 14, paddingHorizontal: 8, borderRadius: 22, backgroundColor: "rgba(255,207,106,0.05)", borderWidth: 1, borderColor: "rgba(255,207,106,0.14)" },
  seatSectionCouple: { gap: 10, paddingVertical: 14, paddingHorizontal: 8, borderRadius: 22, backgroundColor: "rgba(201,63,98,0.06)", borderWidth: 1, borderColor: "rgba(201,63,98,0.18)" },
  seatSectionLabel: { alignSelf: "center", color: palette.muted, fontSize: 10, fontWeight: "800", letterSpacing: 2 },
  seatSectionLabelVip: { alignSelf: "center", color: palette.amber, fontSize: 10, fontWeight: "800", letterSpacing: 2 },
  seatSectionLabelCouple: { alignSelf: "center", color: "#ff89a8", fontSize: 10, fontWeight: "800", letterSpacing: 2 },
  seatRow: { flexDirection: "row", justifyContent: "center", alignItems: "center", gap: 8 },
  seatRowLabel: { width: 18, color: palette.muted, fontSize: 11, textAlign: "center", fontWeight: "800" },
  seatRowLabelVip: { color: palette.amber },
  seatRowLabelCouple: { color: "#ff89a8" },
  seatAisleGap: { width: 10 },
  seatCell: { width: 30, height: 22, borderRadius: 8, alignItems: "center", justifyContent: "center" },
  coupleSeatCell: { width: 56, borderRadius: 12 },
  seatCellText: { color: "#0c1015", fontSize: 8, fontWeight: "900" },
  seatActive: { borderWidth: 2, borderColor: "#ffffff", transform: [{ scale: 1.04 }] },
  legendGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  legendItem: { flexDirection: "row", alignItems: "center", gap: 8, backgroundColor: palette.panelSoft, paddingHorizontal: 12, paddingVertical: 10, borderRadius: 999 },
  legendDot: { width: 12, height: 12, borderRadius: 999 },
  legendText: { color: palette.text, fontSize: 12, fontWeight: "700" },
  bottomSummary: { flexDirection: "row", justifyContent: "space-between", padding: 18, borderRadius: 22, backgroundColor: palette.panelStrong, borderWidth: 1, borderColor: "rgba(195,13,18,0.16)" },
  stickyFooterWrap: { position: "absolute", left: 0, right: 0, bottom: 0, paddingHorizontal: 20, paddingBottom: 18, paddingTop: 14, backgroundColor: "rgba(5,5,7,0.8)" },
  stickyFooter: { borderRadius: 26, padding: 16, backgroundColor: "rgba(20,12,15,0.98)", borderWidth: 1, borderColor: "rgba(195,13,18,0.22)", flexDirection: "row", gap: 14, alignItems: "center", shadowColor: "#000", shadowOpacity: 0.32, shadowRadius: 16, shadowOffset: { width: 0, height: -6 }, elevation: 18 },
  stickySummaryMain: { flex: 1, gap: 4 },
  stickyPrimaryValue: { color: palette.text, fontSize: 18, fontWeight: "900" },
  stickySecondaryValue: { color: palette.muted, fontSize: 12, lineHeight: 18 },
  stickyActionBlock: { minWidth: 148, alignItems: "stretch", gap: 8 },
  summaryLabel: { color: palette.muted, fontSize: 12, fontWeight: "700" },
  summaryValue: { color: palette.text, fontSize: 18, fontWeight: "900", marginTop: 4 },

  comboCard: { flexDirection: "row", justifyContent: "space-between", gap: 12, padding: 18, borderRadius: 22, backgroundColor: palette.panel, borderWidth: 1, borderColor: palette.border },
  comboCardActive: { borderColor: "rgba(115,246,221,0.5)", backgroundColor: "#10211d" },
  comboInfo: { flex: 1, gap: 4 },
  comboTitle: { color: palette.text, fontSize: 16, fontWeight: "800" },
  comboDetail: { color: palette.muted, lineHeight: 20 },
  comboPrice: { color: palette.amber, fontWeight: "900", alignSelf: "center" },
  paymentWrap: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  paymentMethod: { paddingHorizontal: 16, paddingVertical: 11, borderRadius: 999, backgroundColor: palette.panelSoft, borderWidth: 1, borderColor: "rgba(115,246,221,0.18)" },
  paymentMethodActive: { backgroundColor: "rgba(115,246,221,0.13)", borderColor: "rgba(115,246,221,0.7)" },
  paymentMethodText: { color: palette.cyan, fontWeight: "800" },
  paymentMethodTextActive: { color: "#ebfffb" },
  checkoutCard: { backgroundColor: palette.panelStrong, borderRadius: 24, padding: 20, gap: 8, borderWidth: 1, borderColor: "rgba(195,13,18,0.18)" },
  checkoutSummaryGrid: { flexDirection: "row", gap: 10 },
  checkoutSummaryCell: { flex: 1, padding: 16, borderRadius: 18, backgroundColor: palette.panelSoft, borderWidth: 1, borderColor: palette.border },
  checkoutPrice: { color: palette.text, fontSize: 30, fontWeight: "900" },
  checkoutHint: { color: palette.muted, lineHeight: 20 },
  ticketDetailHero: { padding: 22, borderRadius: 26, backgroundColor: palette.panelStrong, borderWidth: 1, borderColor: "rgba(195,13,18,0.18)", gap: 8 },
  ticketDetailGrid: { flexDirection: "row", gap: 10 },

  bottomBar: {
    position: "absolute",
    left: 14,
    right: 14,
    bottom: 14,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    overflow: "hidden",
    backgroundColor: "rgba(18,18,24,0.7)",
    borderRadius: 30,
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    minHeight: 84,
    zIndex: 30,
    elevation: 18,
    shadowColor: "#000",
    shadowOpacity: 0.28,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
  },
  tabItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    paddingHorizontal: 6,
    borderRadius: 22,
    minHeight: 62,
    gap: 5,
    zIndex: 2,
  },
  tabItemActive: {
    position: "absolute",
    left: 10,
    top: 10,
    bottom: 10,
    backgroundColor: palette.red,
    borderWidth: 1,
    borderColor: "rgba(255,232,225,0.18)",
    shadowColor: palette.red,
    shadowOpacity: 0.34,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 14,
  },
  tabIcon: { color: "#716a78" },
  tabIconActive: { color: palette.text },
  tabText: { color: "#716a78", fontSize: 12, fontWeight: "800" },
  tabTextActive: { color: palette.text },
});
