import { StyleSheet } from "react-native";

export const palette = {
  bg: "#09090f",
  panel: "#12121c",
  panelSoft: "#191925",
  panelStrong: "#1f1012",
  text: "#f4f1ec",
  muted: "#9e97a9",
  red: "#c41010",
  redDeep: "#5a0808",
  cyan: "#2df0d0",
  amber: "#ffbf47",
  border: "#2a2436",
  sold: "#444050",
  seat: "#2ec971",
  vip: "#ffbf47",
  couple: "#d9458f",
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: palette.bg },
  topBar: {
    paddingHorizontal: 20, paddingTop: 14, paddingBottom: 12, flexDirection: "row",
    justifyContent: "space-between", alignItems: "center", borderBottomWidth: 1,
    borderBottomColor: "rgba(196,16,16,0.16)", backgroundColor: "#0f0f16",
  },
  brand: { color: palette.amber, fontSize: 12, fontWeight: "800", letterSpacing: 0.8 },
  avatarMini: { width: 34, height: 34, borderRadius: 999, borderWidth: 1, borderColor: "rgba(196,16,16,0.5)", backgroundColor: "#2d0f12" },
  scrollContent: { paddingHorizontal: 20, paddingTop: 20, paddingBottom: 120, gap: 22 },
  toast: { marginHorizontal: 20, marginTop: 12, paddingHorizontal: 16, paddingVertical: 14, borderRadius: 18, backgroundColor: "rgba(20,20,30,0.95)", borderWidth: 1, borderColor: "rgba(255,255,255,0.08)" },
  toastSuccess: { borderColor: "rgba(45,240,208,0.35)", backgroundColor: "rgba(16,35,40,0.96)" },
  toastError: { borderColor: "rgba(196,16,16,0.35)", backgroundColor: "rgba(45,16,18,0.96)" },
  toastText: { color: palette.text, fontWeight: "700", lineHeight: 20 },
  skeletonBlock: { borderRadius: 22, backgroundColor: "#181822", borderWidth: 1, borderColor: "rgba(255,255,255,0.05)" },
  heroCard: { borderRadius: 28, padding: 24, borderWidth: 1, borderColor: "rgba(196,16,16,0.18)", gap: 10, minHeight: 410, overflow: "hidden", justifyContent: "space-between" },
  heroOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(10,10,18,0.42)" },
  heroTopLine: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", zIndex: 1 },
  heroTag: { color: "#fff6e2", fontSize: 12, fontWeight: "800", backgroundColor: "rgba(10,10,18,0.34)", paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999 },
  heroContent: { zIndex: 1, gap: 8, marginTop: 42 },
  heroKicker: { color: "#fff4e8", fontSize: 12, fontWeight: "800", letterSpacing: 1.6 },
  eyebrow: { color: palette.amber, fontSize: 11, fontWeight: "800", letterSpacing: 1.4 },
  heroTitle: { color: palette.text, fontSize: 42, lineHeight: 46, fontWeight: "900" },
  heroSubline: { color: "#ffede6", fontSize: 13, fontWeight: "700" },
  heroBody: { color: "#f2dde0", fontSize: 15, lineHeight: 22 },
  heroMetrics: { zIndex: 1, flexDirection: "row", gap: 10 },
  metricItem: { flex: 1, borderRadius: 18, padding: 14, backgroundColor: "rgba(10,10,18,0.34)", borderWidth: 1, borderColor: "rgba(255,255,255,0.08)" },
  metricLabel: { color: "#cfccd8", fontSize: 11, fontWeight: "700" },
  metricValue: { color: "#fff", fontSize: 15, fontWeight: "900", marginTop: 6 },
  heroActions: { flexDirection: "row", gap: 10, marginTop: 8, zIndex: 1 },
  quickStrip: { flexDirection: "row", gap: 10 },
  quickStripItem: { flex: 1, padding: 16, borderRadius: 18, backgroundColor: palette.panelSoft, borderWidth: 1, borderColor: "rgba(255,255,255,0.06)" },
  quickStripLabel: { color: palette.muted, fontSize: 11, fontWeight: "700" },
  quickStripValue: { color: palette.text, fontSize: 16, fontWeight: "900", marginTop: 6 },
  button: { paddingHorizontal: 18, paddingVertical: 12, borderRadius: 999 },
  buttonPrimary: { backgroundColor: palette.red },
  buttonSecondary: { borderWidth: 1, borderColor: "rgba(255,255,255,0.18)", backgroundColor: "transparent" },
  buttonText: { fontSize: 13, fontWeight: "800" },
  buttonTextPrimary: { color: "#fff4f2" },
  buttonTextSecondary: { color: palette.text },
  sectionHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  sectionTitle: { color: palette.text, fontSize: 26, fontWeight: "900" },
  sectionAction: { color: palette.amber, fontSize: 12, fontWeight: "800" },
  row: { gap: 14, paddingRight: 12 },
  bannerCard: { width: 280, borderRadius: 24, padding: 18, gap: 8 },
  bannerEyebrow: { color: "#f0d8d4", fontSize: 11, fontWeight: "800", letterSpacing: 0.8 },
  bannerTitle: { color: "#fff", fontSize: 30, fontWeight: "900" },
  bannerText: { color: "#ece6ff", fontSize: 14, lineHeight: 20 },
  bannerLink: { color: "#fff5c8", fontWeight: "800", marginTop: 10 },
  movieCard: { width: 180, gap: 10 },
  poster: { height: 230, borderRadius: 22, justifyContent: "flex-end", padding: 14, overflow: "hidden" },
  posterScrim: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(10,10,18,0.16)" },
  posterBadge: { color: "#fff", fontSize: 11, fontWeight: "800", paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, backgroundColor: "rgba(9,9,15,0.42)", alignSelf: "flex-start" },
  movieTitle: { color: palette.text, fontSize: 18, fontWeight: "800" },
  movieMeta: { color: palette.muted, fontSize: 12 },
  movieFooter: { flexDirection: "row", justifyContent: "space-between" },
  movieScore: { color: palette.amber, fontWeight: "900" },
  movieAction: { color: palette.text, fontWeight: "700" },
  rankingWrap: { gap: 12 },
  rankingRow: { flexDirection: "row", gap: 14, alignItems: "center", padding: 16, backgroundColor: palette.panel, borderWidth: 1, borderColor: "rgba(255,255,255,0.06)", borderRadius: 20 },
  rankNumber: { color: "rgba(255,255,255,0.18)", fontSize: 32, fontWeight: "900" },
  rankMain: { flex: 1, gap: 4 },
  rankMovie: { color: palette.text, fontWeight: "800", fontSize: 16 },
  rankRevenue: { color: palette.cyan, fontWeight: "800", fontSize: 12 },
  rankAction: { paddingHorizontal: 14, paddingVertical: 10, borderRadius: 999, backgroundColor: "rgba(196,16,16,0.16)", borderWidth: 1, borderColor: "rgba(196,16,16,0.36)" },
  rankActionText: { color: "#fff3f0", fontWeight: "800", fontSize: 12 },
  exploreHero: { padding: 22, backgroundColor: palette.panelStrong, borderRadius: 24, borderWidth: 1, borderColor: "rgba(196,16,16,0.16)", gap: 8 },
  exploreCard: { backgroundColor: palette.panel, borderRadius: 24, overflow: "hidden", borderWidth: 1, borderColor: "rgba(255,255,255,0.05)" },
  explorePoster: { height: 180 },
  exploreBody: { padding: 18, gap: 6 },
  exploreBadge: { color: palette.amber, fontSize: 11, fontWeight: "800" },
  exploreTitle: { color: palette.text, fontSize: 21, fontWeight: "900" },
  exploreMeta: { color: palette.cyan, fontSize: 12, fontWeight: "700" },
  exploreDescription: { color: palette.muted, lineHeight: 20 },
  screenIntro: { gap: 8 },
  ticketCard: { backgroundColor: palette.panel, borderRadius: 24, borderWidth: 1, borderColor: "rgba(255,255,255,0.06)", overflow: "hidden" },
  ticketEmptyCard: { backgroundColor: palette.panelStrong, borderRadius: 24, borderWidth: 1, borderColor: "rgba(196,16,16,0.14)", padding: 18, gap: 14 },
  ticketEmptyLabel: { color: palette.amber, fontSize: 11, fontWeight: "800", letterSpacing: 1.4 },
  ticketStripe: { height: 5, backgroundColor: palette.red },
  ticketHead: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 10 },
  ticketContent: { padding: 18, gap: 6 },
  ticketMovie: { color: palette.text, fontSize: 18, fontWeight: "900" },
  ticketInfo: { color: palette.muted, lineHeight: 19 },
  ticketStatus: { color: "#ffe8e8", fontSize: 11, fontWeight: "800", borderWidth: 1, borderColor: "rgba(255,255,255,0.08)", backgroundColor: "rgba(255,255,255,0.06)", borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6 },
  ticketStatusPaid: { color: "#ddfff7", borderColor: "rgba(45,240,208,0.24)", backgroundColor: "rgba(45,240,208,0.12)" },
  profileHero: { flexDirection: "row", alignItems: "center", gap: 16, backgroundColor: palette.panelStrong, borderWidth: 1, borderColor: "rgba(196,16,16,0.16)", borderRadius: 26, padding: 20 },
  avatar: { width: 60, height: 60, borderRadius: 999, backgroundColor: "#2b0e12", borderWidth: 1, borderColor: "rgba(196,16,16,0.4)" },
  profileName: { color: palette.text, fontSize: 20, fontWeight: "900" },
  profileMail: { color: palette.muted },
  accountRow: { padding: 18, borderRadius: 22, backgroundColor: palette.panel, borderWidth: 1, borderColor: "rgba(255,255,255,0.05)", gap: 4 },
  accountTitle: { color: palette.text, fontSize: 16, fontWeight: "800" },
  accountDetail: { color: palette.muted, lineHeight: 20 },
  profileMovieList: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginTop: 10 },
  profileMovieChip: { paddingHorizontal: 12, paddingVertical: 10, borderRadius: 999, backgroundColor: palette.panelSoft, borderWidth: 1, borderColor: "rgba(255,255,255,0.06)" },
  profileMovieChipText: { color: palette.text, fontSize: 12, fontWeight: "700" },
  activityRow: { paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: "rgba(255,255,255,0.05)", gap: 4 },
  activityTitle: { color: palette.text, fontSize: 14, fontWeight: "800" },
  activityMeta: { color: palette.muted, fontSize: 12, lineHeight: 18 },
  activityTime: { color: palette.cyan, fontSize: 11, fontWeight: "700" },
  input: { marginTop: 10, borderRadius: 16, backgroundColor: palette.panelSoft, borderWidth: 1, borderColor: "rgba(255,255,255,0.08)", color: palette.text, paddingHorizontal: 14, paddingVertical: 12 },
  backLink: { color: palette.cyan, fontSize: 13, fontWeight: "800" },
  detailPoster: { height: 260, borderRadius: 28, justifyContent: "flex-end", padding: 18, overflow: "hidden" },
  detailPosterScrim: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(10,10,18,0.24)" },
  detailOverlayMeta: { position: "absolute", top: 18, right: 18, gap: 8 },
  detailOverlayText: { color: "#fff6eb", fontSize: 11, fontWeight: "800", backgroundColor: "rgba(10,10,18,0.32)", borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6 },
  detailTitle: { color: palette.text, fontSize: 32, lineHeight: 38, fontWeight: "900" },
  detailMeta: { color: palette.cyan, fontSize: 13, fontWeight: "700" },
  detailDescription: { color: palette.muted, lineHeight: 22, fontSize: 15 },
  detailActionsRow: { flexDirection: "row", gap: 10, flexWrap: "wrap" },
  detailStatsRow: { flexDirection: "row", gap: 10 },
  detailStat: { flex: 1, padding: 16, borderRadius: 18, backgroundColor: palette.panelSoft, borderWidth: 1, borderColor: "rgba(255,255,255,0.06)" },
  detailStatLabel: { color: palette.muted, fontSize: 11, fontWeight: "700" },
  detailStatValue: { color: palette.text, fontSize: 15, fontWeight: "900", marginTop: 6 },
  showtimeGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  showtimeCard: { width: "47%", backgroundColor: palette.panel, borderRadius: 18, padding: 16, borderWidth: 1, borderColor: "rgba(255,255,255,0.06)", gap: 4 },
  showtimeTime: { color: palette.text, fontSize: 20, fontWeight: "900" },
  showtimeInfo: { color: palette.muted, fontSize: 12 },
  showtimePrice: { color: palette.amber, fontSize: 13, fontWeight: "900", marginTop: 8 },
  detailFactWrap: { backgroundColor: palette.panel, borderRadius: 22, padding: 18, borderWidth: 1, borderColor: "rgba(255,255,255,0.06)", gap: 10 },
  detailFact: { color: palette.text, lineHeight: 22 },
  seatHeader: { gap: 6 },
  seatPriceRow: { flexDirection: "row", gap: 10 },
  seatPriceCard: { flex: 1, padding: 14, borderRadius: 18, backgroundColor: palette.panelSoft, borderWidth: 1, borderColor: "rgba(255,255,255,0.06)" },
  seatPriceLabel: { color: palette.muted, fontSize: 11, fontWeight: "700" },
  seatPriceValue: { color: palette.text, fontSize: 15, fontWeight: "900", marginTop: 6 },
  screenArcWrap: { alignItems: "center", gap: 10 },
  screenArcGlow: { width: "86%", height: 8, borderRadius: 999, backgroundColor: "rgba(45,240,208,0.35)" },
  screenArcText: { color: palette.cyan, fontSize: 11, fontWeight: "800", letterSpacing: 2 },
  seatGridWrap: { backgroundColor: palette.panel, borderRadius: 28, padding: 18, borderWidth: 1, borderColor: "rgba(255,255,255,0.06)", gap: 10 },
  seatRow: { flexDirection: "row", justifyContent: "center", gap: 8 },
  seatCell: { width: 28, height: 22, borderRadius: 8, alignItems: "center", justifyContent: "center" },
  seatCellText: { color: "#0c1015", fontSize: 8, fontWeight: "800" },
  seatActive: { borderWidth: 2, borderColor: "#ffffff", transform: [{ scale: 1.05 }] },
  legendGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  legendItem: { flexDirection: "row", alignItems: "center", gap: 8, backgroundColor: palette.panelSoft, paddingHorizontal: 12, paddingVertical: 10, borderRadius: 999 },
  legendDot: { width: 12, height: 12, borderRadius: 999 },
  legendText: { color: palette.text, fontSize: 12, fontWeight: "700" },
  bottomSummary: { flexDirection: "row", justifyContent: "space-between", padding: 18, borderRadius: 22, backgroundColor: palette.panelStrong, borderWidth: 1, borderColor: "rgba(196,16,16,0.14)" },
  summaryLabel: { color: palette.muted, fontSize: 12, fontWeight: "700" },
  summaryValue: { color: palette.text, fontSize: 18, fontWeight: "900", marginTop: 4 },
  comboCard: { flexDirection: "row", justifyContent: "space-between", gap: 12, padding: 18, borderRadius: 22, backgroundColor: palette.panel, borderWidth: 1, borderColor: "rgba(255,255,255,0.06)" },
  comboCardActive: { borderColor: "rgba(45,240,208,0.6)", backgroundColor: "#102328" },
  comboTitle: { color: palette.text, fontSize: 16, fontWeight: "800" },
  comboDetail: { color: palette.muted, lineHeight: 20 },
  comboPrice: { color: palette.amber, fontWeight: "900", alignSelf: "center" },
  paymentWrap: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  paymentMethod: { paddingHorizontal: 16, paddingVertical: 11, borderRadius: 999, backgroundColor: palette.panelSoft, borderWidth: 1, borderColor: "rgba(45,240,208,0.16)" },
  paymentMethodActive: { backgroundColor: "rgba(45,240,208,0.12)", borderColor: "rgba(45,240,208,0.65)" },
  paymentMethodText: { color: palette.cyan, fontWeight: "800" },
  paymentMethodTextActive: { color: "#ebfffb" },
  checkoutCard: { backgroundColor: palette.panelStrong, borderRadius: 24, padding: 20, gap: 8, borderWidth: 1, borderColor: "rgba(196,16,16,0.18)" },
  checkoutSummaryGrid: { flexDirection: "row", gap: 10 },
  checkoutSummaryCell: { flex: 1, padding: 16, borderRadius: 18, backgroundColor: palette.panelSoft, borderWidth: 1, borderColor: "rgba(255,255,255,0.06)" },
  checkoutPrice: { color: palette.text, fontSize: 30, fontWeight: "900" },
  checkoutHint: { color: palette.muted, lineHeight: 20 },
  ticketDetailHero: { padding: 22, borderRadius: 26, backgroundColor: palette.panelStrong, borderWidth: 1, borderColor: "rgba(196,16,16,0.16)", gap: 8 },
  ticketDetailGrid: { flexDirection: "row", gap: 10 },
  bottomBar: { position: "absolute", left: 16, right: 16, bottom: 16, flexDirection: "row", justifyContent: "space-between", alignItems: "center", backgroundColor: "#14141d", borderRadius: 26, paddingVertical: 14, paddingHorizontal: 10, borderWidth: 1, borderColor: "rgba(196,16,16,0.12)" },
  tabItem: { flex: 1, alignItems: "center" },
  tabText: { color: "#6d6879", fontSize: 12, fontWeight: "800" },
  tabTextActive: { color: palette.text },
});
